spring:
  datasource:
    url: jdbc:h2:mem:tracker
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #validate / update/ create / create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console